
name: CD

# on:
#   workflow_dispatch:

on:
  push:
    branches:
      - developement_v1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Deploy app using docker-compose
      run: docker-compose up -d --build
    
